services:
  - type: web
    name: squaas-backend
    runtime: python
    region: oregon
    plan: free
    buildCommand: "pip install poetry && poetry install"
    startCommand: "poetry run uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: POETRY_VERSION
        value: 1.7.1
    healthCheckPath: /

